name: Build and Deploy
on:
  push:
    branches:
      - navlinks # change to `master` before merging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Generate Builds
        run: |
          ${GITHUB_WORKSPACE}/scripts/layercake/generate.sh
      - name: Check that `/docs` exists
        run: |
          [ -d ${GITHUB_WORKSPACE}/docs ] && echo "/docs exists" || exit 1
      # put tests here
      - name: Deploy `docs`
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
      - name: Check that `/gh-pages` exists
        run: |
          [ -d ${GITHUB_WORKSPACE}/gh-pages ] && echo "/gh-pages exists" || exit 1
      - name: Deploy `gh-pages`
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages
          CLEAN: true
