name: Build and Deploy
on:
  push:
    branches:
      - navlinks # change to `master` before merging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install and Build
        run: |
          ${GITHUB_WORKSPACE}/scripts/layercake/generate.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages
          CLEAN: true
