name: Build and Deploy
on:
  push:
    branches:
      - navlinks # change to `master` before merging
jobs:
  build-docs:
    name: Build `docs`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Generate `docs`
        run: |
          ${GITHUB_WORKSPACE}/scripts/layercake/generate.sh
      - name: Check that `/docs` exists
        run: |
          [ -d ${GITHUB_WORKSPACE}/docs ] && echo "/docs exists" || exit 1
      - name: Upload `docs` artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: docs
      - name: Deploy `docs`
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs
          CLEAN: true
  build-gh-pages:
    name: Build `gh-pages`
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download `docs` artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact
          path: docs
      - name: Generate `gh-pages`
        run: |
          #!/bin/bash
          [ -d ${GITHUB_WORKSPACE}/docs/ ] && echo "/docs exists" || exit 1
          cp -r ${GITHUB_WORKSPACE}/docs/ ${GITHUB_WORKSPACE}/gh-pages/
          shopt -s extglob
          sed -i "s/\.md/\.html/" ${GITHUB_WORKSPACE}/gh-pages/misc/*.@(gv|svg)
          [ -d ${GITHUB_WORKSPACE}/gh-pages/ ] && echo "/gh-pages exists" || exit 1
      - name: Deploy `gh-pages`
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages
          CLEAN: true
  test-docs:
    name: Test Cryptol modules in `/docs`
    # strategy:
    #   matrix:
    #     os:
    #       - macos-latest
    #       - ubuntu-latest
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download `docs` artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact
          path: docs
      # - name: Install OS-specific releases of Cryptol, SAW, and Z3
      #   run: |
      #     ${GITHUB_WORKSPACE}/scripts/install-deps-ubuntu-latest.sh
      # - name: Run test script
      #   run: |
      #     ${GITHUB_WORKSPACE}/scripts/test_cryptol_modules.sh
