name: Render to Local Browsing and GitHub Pages
on:
  push:
    branches:
      - navlinks  # change to `master` before merging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - # remove before merging to `master`
        name: Switch to Current Branch  
        run: git checkout ${{ env.BRANCH }}
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Run Poetry Image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Generate Local Markdown and GitHub Pages Views
        run:
          ${GITHUB_WORKSPACE}/scripts/layercake/generate_github_action.sh
        shell:
          bash
